---
title: "Initial Korean covid 19"
author: "Colton Beardsley"
date: "10/10/23"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits=2)
require(tidyverse)
require(tigerstats)
require(lubridate)
kRdata <- read.csv(file = 'kRdata.csv')
kRdata <- kRdata %>%
mutate(across(where(is.character), as.factor))

```
### Data is from the Patient_Info dataset from South Korea 1 Jan to 1 May 2020
### This data was retrieved from a downloadable zip file from kaggle

Some of the data was uncoded for sex - sex must be just male or female
77 of the data entries were coded sex  as blank, so we omit these.
state of a patient must be died or alive - we adjust that as well   
  
# Your Question - Is dying independent of sex?


# Method

Based on the data we found in kRdata, we will try to find out if there's a difference between men and women. Is there any difference in how COVID kills men and women? Is COVID more harmful to men? Or is it more harmful to women? 

This appears to be a category-category problem. Therefore, we will be deploying cat-cat helper files to run a test. 


## Graphical results - use ggplot commands to do this  



  





  
## Numerical results




## Inferential results 



Based on the result of the chisq and fisher test, the result shows that if you are a male then you are twice as likely to die from covid than a women.

## Conclusions

